version: "3"
services:
 hub:
   image: selenium/hub:4.8.2
   ports:
     - "4444:4444"
 chrome:
   image: selenium/node-chrome:4.9.1
   shm_size: '2g'
   depends_on:
     - hub   
   environment:
     - SE_EVENT_BUS_HOST=hub
     - SE_EVENT_BUS_PUBLISH_PORT=4442
     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
 firefox:
   image: selenium/node-firefox:4.9.1
   shm_size: '2g'
   depends_on:
     - hub   
   environment:
     - SE_EVENT_BUS_HOST=hub
     - SE_EVENT_BUS_PUBLISH_PORT=4442
     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
 OpenNewAccountTests:
   image: wzard94/parabankdocker
   depends_on:
     - chrome
     - firefox
   environment:
     - BROWSER=chrome
     - XML=OpenNewAccountTests.xml
     - HUB_HOST=hub
   volumes:
     - ./TestOutput/OpenNewAccountTests:/usr/parabankTests/test-output  